name: Build Project

#on:
#  pull_request:
#    branches: [main, master, develop]

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches:
      - master
      - releases/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Gradle
      run: ./gradlew clean build
