name: Create Docker Image

#on:
#  push:
#    branches:
#      - releases/**

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches:
      - master
      - releases/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
#      - name: Build Docker Image
#        run: ./gradlew jibDockerBuild
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: ./gradlew jib